### ISSUE TITLE
does it work with gpt4?

### ISSUE THREAD

**Issue by runawaydevil** [askrella/whatsapp-chatgpt#219]
I believe i should put the org and the key...
how does it works?

**Comment by adamshand** [comment]
If you are running via Docker you just need to set the OPENAI_GPT_MODELvariables in your docker-compose.yml,  e.g.

```
services:
  whatsapp_bot:
    image: ghcr.io/askrella/whatsapp-chatgpt:master
    container_name: whatsapp_bot
    environment:
      PREFIX_ENABLED: "true"
      GROUPCHATS_ENABLED: "true"
      OPENAI_API_KEY: "sk-xxxx"
      OPENAI_GPT_MODEL: "gpt-4"
      SERPAPI_API_KEY: "xxxx"
      HUGGINGFACE_API_TOKEN: "hf_xxx"
    volumes:
      - ./app/session:/app/session
```
